name: Commit Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Conda and Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: neuroceiling
        python-version: ${{ matrix.python-version }}
    - name: Current env
      run: |
        conda info --envs
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Check formatting with black
      uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./src"
        use_pyproject: true
    - name: Analysing the code with pylint
      run: |
        pylint src/